# Generated by Django 5.2.3 on 2026-06-09 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('indexing', 'Индексируется'), ('indexed', 'Готов'), ('error', 'Ошибка')], default='pending', max_length=20)),
                ('progress', models.TextField(blank=True, default='')),
                ('error_msg', models.TextField(blank=True, default='')),
                ('text_chunks', models.IntegerField(default=0)),
                ('images_count', models.IntegerField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
